CREATE SCHEMA IF NOT EXISTS lab2;

CREATE ROLE migrate NOINHERIT LOGIN PASSWORD 'migrate' NOCREATEDB;
GRANT USAGE ON SCHEMA lab2 TO migrate;
GRANT CREATE ON SCHEMA lab2 TO migrate;

CREATE ROLE app NOINHERIT LOGIN PASSWORD 'app' NOCREATEDB;
GRANT USAGE ON SCHEMA lab2 TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lab2 to app;
